app:
  name: "cinematic"
http:
  port: ":8009"
  host: "localhost"
  read_timeout: 60
  mode: "dev"
service:
  secret: "V+Q4mtGLNYcC/tKIbqa05T0W06spY71ciWe/qmbEL7DybUW9ujIyQ8jkIamUKxP2wdcs4xnTRGSiDxJO"
postgres:
  postgres_password: password
  postgres_user: cinematic
  postgres_database: cinematic
  postgres_host: localhost
  postgres_port: 5432
