app:
  name: "cinematic"
http:
  port: ":8009"
  host: "localhost"
  read_timeout: 60
  mode: "dev"
postgres:
  postgres_password: "password"
  postgres_user: "cinematic"
  postgres_database: cinematic
  postgres_host: "localhost"
  postgres_port: 5432
